# backend/alembic/script.py.mako - Migration Template

"""increase refresh token length for jwt

Revision ID: 3241efe46832
Revises: 47252dfa67d3
Create Date: 2025-08-11 21:05:43.056496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3241efe46832'
down_revision: Union[str, None] = '47252dfa67d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_users', 'role',
               existing_type=postgresql.ENUM('USER', 'ADMIN', 'SUPERUSER', name='user_role_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'token',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('auth_users', 'role',
               existing_type=postgresql.ENUM('USER', 'ADMIN', 'SUPERUSER', name='user_role_enum'),
               server_default=sa.text("'USER'::user_role_enum"),
               existing_nullable=False)
    # ### end Alembic commands ###
