# backend/alembic/script.py.mako - Migration Template

"""Fix foreign key references from users to auth_users

Revision ID: f6774a10220d
Revises: 3241efe46832
Create Date: 2025-08-13 13:46:26.838081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6774a10220d'
down_revision: Union[str, None] = '3241efe46832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # Drop existing foreign key constraints that reference users table
    op.drop_constraint('entries_user_id_fkey', 'entries', type_='foreignkey')
    op.drop_constraint('topics_user_id_fkey', 'topics', type_='foreignkey')
    op.drop_constraint('chat_sessions_user_id_fkey', 'chat_sessions', type_='foreignkey')
    op.drop_constraint('entry_templates_created_by_user_id_fkey', 'entry_templates', type_='foreignkey')
    
    # Add new foreign key constraints that reference auth_users table
    op.create_foreign_key('entries_user_id_fkey', 'entries', 'auth_users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('topics_user_id_fkey', 'topics', 'auth_users', ['user_id'], ['id'], ondelete='CASCADE')  
    op.create_foreign_key('chat_sessions_user_id_fkey', 'chat_sessions', 'auth_users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('entry_templates_created_by_user_id_fkey', 'entry_templates', 'auth_users', ['created_by_user_id'], ['id'], ondelete='SET NULL')


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
